eco_disabled=\u274C Modu\u0142 ekonomii jest wy\u0142\u0105czony na tym serwerze.
bot_profile=\u274C Boty nie posiadaj\u0105 profilu ekonomicznego.
profile_title=Profil: {0}
profile_desc=\uD83D\uDCB0 **Portfel:** {0} {1} {2}\n\uD83C\uDFC6 **Poziom:** {3}\n\u2728 **Do\u015Bwiadczenie:** {4} / {5} XP\n\uD83D\uDC3E **Zwierzak:** {6}
cooldown_work=\u23F3 Zm\u0119czy\u0142e\u015B si\u0119! Mo\u017Cesz pracowa\u0107 za {0} sekund.
work_earned=Zarobi\u0142e\u015B **{0} {1}**\n\u2728 Zdobywasz **{2} XP**!
pet_bonus=\n\uD83D\uDC3E *(W tym aktywny bonus od najedzonego zwierzaka!)*
level_up=\n\n\uD83C\uDF89 **AWANS!** Osi\u0105gasz **{0} poziom**!
cooldown_daily=\u23F3 Odbi\u00F3r mo\u017Cliwy za ok. {0} godzin.
daily_earned=Odebra\u0142e\u015B codzienn\u0105 nagrod\u0119: **{0} {1}**\n\u2728 Zdobywasz ogromny bonus **{2} XP**!
shop_title=\uD83D\uDED2 Sklep Serwerowy
shop_desc=Wymie\u0144 swoje {0} **{1}** na ekskluzywne nagrody, rangi VIP i kody do gier!\n\n\uD83D\uDC49 **[Kliknij tutaj, aby otworzy\u0107 sklep]({2})**
err_args=\u274C B\u0142\u0105d: Upewnij si\u0119, \u017Ce poda\u0142e\u015B odpowiednie argumenty!
err_self_bot=\u274C Nie mo\u017Cesz wykona\u0107 tej akcji na sobie ani na bocie.
err_amount=\u274C Podano nieprawid\u0142ow\u0105 kwot\u0119.
err_funds=\u274C Nie masz wystarczaj\u0105co du\u017Co waluty.
pay_success=\uD83D\uDCB8 Pomy\u015Blnie przelano **{0} {1}** do <@{2}>! (Pobrano {3} podatku)
pay_received=\uD83D\uDCB8 Otrzyma\u0142e\u015B **{0} {1}** od <@{2}>!
cf_win=\uD83C\uDFB2 Wygrywasz rzut monet\u0105! Zdobywasz **{0} {1}**.
cf_lose=\uD83C\uDFB2 Niestety, przegrywasz. Tracisz **{0} {1}**.
market_title=\uD83D\uDCCA Gie\u0142da Wirtualna
market_desc=Ceny na gie\u0142dzie zmieniaj\u0105 si\u0119 dynamicznie. Kupuj tanio, sprzedawaj drogo!\n\n**Aktualne notowania sp\u00F3\u0142ek:**
market_footer=Notowania od\u015Bwie\u017Caj\u0105 si\u0119 automatycznie co 10 minut.
market_buy_ok=\uD83D\uDCC8 **KUPNO ZAKO\u0143CZONE!**\nZakupi\u0142e\u015B **{0}x {1}** po kursie **{2}** za sztuk\u0119.\n\u0141\u0105czny koszt: **{3} {4}**.
market_buy_fail=\u274C Nie sta\u0107 Ci\u0119 na te akcje. Potrzebujesz **{0} {1}**.
market_sell_ok=\uD83D\uDCC9 **SPRZEDA\u017B ZAKO\u0143CZONA!**\nSprzeda\u0142e\u015B **{0}x {1}** po kursie **{2}** za sztuk\u0119.\nTw\u00F3j zysk: **{3} {4}**.
market_sell_fail=\u274C Nie masz tylu akcji! Posiadasz tylko **{0}x {1}**.
pet_disabled=\u274C System zwierzak\u00F3w jest wy\u0142\u0105czony.
pet_title=\uD83D\uDC3E Centrum Zwierzak\u00F3w
pet_desc=Tw\u00F3j zwierzak to Tw\u00F3j najlepszy partner biznesowy. Daje Ci pasywne bonusy do zarobk\u00F3w i expa, o ile pami\u0119tasz, by go regularnie karmi\u0107!
pet_btn_buy=\uD83D\uDED2 Kup
pet_btn_feed=\uD83C\uDF56 Nakarm
pet_btn_status=\uD83D\uDCCA Status
admin_err_perm=\u274C Brak uprawnie\u0144!
admin_success=\u2705 Pomy\u015Blnie dodano **{0} {1}** do portfela u\u017Cytkownika <@{2}>!
stats_title=\uD83D\uDCC8 Globalne Statystyki Bota
stats_desc=Poni\u017Cej znajdziesz informacje o wykorzystaniu naszego bota na ca\u0142ym \u015Bwiecie!
stats_servers=\uD83C\uDF0D Aktywne serwery
stats_cmds_24h=\u26A1 Komendy (Ostatnie 24h)
stats_cmds_total=\uD83D\uDCBE Komendy (\u0141\u0105cznie)
heist_active=\u274C Na tym serwerze trwa ju\u017C przygotowanie do napadu! Do\u0142\u0105cz do akcji zanim wyjad\u0105!
heist_no_funds=\u274C Jeste\u015B zbyt sp\u0142ukany na tak\u0105 akcj\u0119. Wpisowe to **{0} {1}**.
heist_title=\uD83D\uDEA8 NAPAD W TOKU! \uD83D\uDEA8
heist_desc=<@{0}> zbiera ekip\u0119 na skok na Bank Serwera!\n\n**Wpisowe:** {1} {2}\n**Czas na zbi\u00F3rk\u0119:** {3}\n\nEkipa: {4} os.\n*Kliknij przycisk poni\u017Cej, \u017Ceby do\u0142\u0105czy\u0107. Uwaga: Je\u015Bli Was z\u0142api\u0105, traficie do wi\u0119zienia (Timeout na 5 minut)!*
heist_btn_join=\uD83D\uDD2B Wchodz\u0119 w to! ({0})
heist_cancel_title=\uD83D\uDE93 Akcja Odwo\u0142ana
heist_cancel_desc=Ekipa by\u0142a za ma\u0142a (Minimum 3 osoby). Zwin\u0119li\u015Bcie si\u0119 zanim przyjecha\u0142a policja. Wpisowe zosta\u0142o zwr\u00F3cone.
heist_win_title=\uD83D\uDCB0 SUKCES! Skarbiec Rozbity!
heist_win_desc=Byli\u015Bcie nieuchwytni! Ekipa uciek\u0142a z workami pe\u0142nymi got\u00F3wki.\n\n**Ca\u0142kowity \u0142up:** {0} {1}\n**Na g\u0142ow\u0119:** {2} {3}\n\n**Ekipa:** {4}
heist_lose_title=\uD83D\uDE93 WPADKA! Policja na miejscu!
heist_lose_desc=Alarmy wy\u0142y za g\u0142o\u015Bno, odci\u0119li Wam ucieczk\u0119. Tracicie wpisowe i l\u0105dujecie w celi!\n\n**Z\u0142apani (5 minut ciszy):** {0}
heist_err_ended=\u274C Ten napad si\u0119 ju\u017C zako\u0144czy\u0142!
heist_err_in=\u274C Jeste\u015B ju\u017C w ekipie! Przygotuj sprz\u0119t.
heist_join_ok=\u2705 Kupi\u0142e\u015B mask\u0119. Do\u0142\u0105czy\u0142e\u015B do ekipy!
pet_err_not_yours=\u274C To nie jest Tw\u00F3j panel!
pet_err_has_pet=\u274C Masz ju\u017C zwierzaka! Nie mo\u017Cesz kupi\u0107 kolejnego.
pet_shop_title=\uD83D\uDED2 Sklep ze Zwierzakami
pet_shop_desc=Wybierz kompana. Pami\u0119taj, \u017Ce musisz go karmi\u0107 co 24 godziny!
pet_shop_field=Cena: **{0}** {1}\nMno\u017Cnik: Kasa x{2} | Exp x{3}
pet_err_not_found=\u274C B\u0142\u0105d: Nie znaleziono tego zwierzaka!
pet_buy_ok=\uD83C\uDF89 Pomy\u015Blnie kupi\u0142e\u015B: **{0}**!
pet_err_no_pet=\u274C Nie masz zwierzaka do nakarmienia.
pet_feed_ok=\uD83C\uDF56 Tw\u00F3j zwierzak zosta\u0142 pomy\u015Blnie nakarmiony i jego mno\u017Cniki s\u0105 aktywne przez nast\u0119pne 24 godziny! (Pobrano {0} {1})
pet_feed_fail=\u274C Nie sta\u0107 Ci\u0119 na karm\u0119! Kosztuje {0} {1}
pet_status_title=\uD83D\uDCCA Status Twojego Zwierzaka
pet_status_happy=**{0}** jest radosny i najedzony!\n\n\u2728 **Aktywny Mno\u017Cnik Kasy:** x{1}\n\u2728 **Aktywny Mno\u017Cnik EXP:** x{2}\n\n\u23F3 B\u0119dzie g\u0142odny za ok. **{3} godzin**.
pet_status_sad=**{0}** jest wyg\u0142odnia\u0142y!\n\n\u274C **Mno\u017Cniki s\u0105 WY\u0141\u0104CZONE (x1.0)**.\nNakarm go z panelu g\u0142\u00F3wnego, aby przywr\u00F3ci\u0107 bonusy!